{"publishedDate": "2019-06-06T19:29Z", "lastModifiedDate": "2024-11-21T04:23Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2019-12761", "ASSIGNER": "cve@mitre.org"}, "description": {"description_data": [{"lang": "en", "value": "A code injection issue was discovered in PyXDG before 0.26 via crafted Python code in a Category element of a Menu XML document in a .menu file. XDG_CONFIG_DIRS must be set up to trigger xdg.Menu.parse parsing within the directory containing this file. This is due to a lack of sanitization in xdg/Menu.py before an eval call."}, {"lang": "es", "value": "Se descubri\u00f3 un problema de inyecci\u00f3n de c\u00f3digo en PyXDG antes de 0.26 a trav\u00e9s del c\u00f3digo Python creado en un elemento de Categor\u00eda de un documento de Men\u00fa XML en un archivo .men\u00fa. XDG_CONFIG_DIRS debe configurarse para activar el an\u00e1lisis xdg.Menu.parse dentro del directorio que contiene este archivo. Esto es debido a la falta de desinfecci\u00f3n en xdg / Menu.py antes de una llamada de evaluaci\u00f3n."}]}, "references": {"reference_data": [{"url": "https://gist.github.com/dhondta/b45cd41f4186110a354dc7272916feba", "name": "", "refsource": "", "tags": ["Exploit", "Third Party Advisory"]}, {"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00006.html", "name": "", "refsource": "", "tags": []}, {"url": "https://lists.debian.org/debian-lts-announce/2021/08/msg00003.html", "name": "", "refsource": "", "tags": []}, {"url": "https://snyk.io/vuln/SNYK-PYTHON-PYXDG-174562", "name": "", "refsource": "", "tags": ["Third Party Advisory"]}, {"url": "https://gist.github.com/dhondta/b45cd41f4186110a354dc7272916feba", "name": "", "refsource": "", "tags": ["Exploit", "Third Party Advisory"]}, {"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00006.html", "name": "", "refsource": "", "tags": []}, {"url": "https://lists.debian.org/debian-lts-announce/2021/08/msg00003.html", "name": "", "refsource": "", "tags": []}, {"url": "https://snyk.io/vuln/SNYK-PYTHON-PYXDG-174562", "name": "", "refsource": "", "tags": ["Third Party Advisory"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-94"}]}]}}, "impact": {"baseMetricV2": {"cvssV2": {"version": "2.0", "vectorString": "AV:N/AC:H/Au:N/C:P/I:P/A:P", "baseScore": 5.1, "accessVector": "NETWORK", "accessComplexity": "HIGH", "authentication": "NONE", "confidentialityImpact": "PARTIAL", "integrityImpact": "PARTIAL", "availabilityImpact": "PARTIAL"}, "exploitabilityScore": 4.9, "impactScore": 6.4, "severity": "MEDIUM", "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": true}, "baseMetricV3": {"exploitabilityScore": 1.6, "impactScore": 5.9, "cvssV3": {"version": "3.0", "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H", "baseScore": 7.5, "baseSeverity": "HIGH", "attackVector": "NETWORK", "attackComplexity": "HIGH", "privilegesRequired": "NONE", "userInteraction": "REQUIRED", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:python:pyxdg:*:*:*:*:*:*:*:*", "matchCriteriaId": "49D2B0BB-1F21-4EB5-A39A-E2B8DA2B718B", "cpe_name": [], "versionEndExcluding": "0.26"}]}]}}