{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-38593", "ASSIGNER": "cve@kernel.org"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://git.kernel.org/stable/c/3ddf170e4a604f5d4d9459a36993f5e92b53e8b0", "name": "https://git.kernel.org/stable/c/3ddf170e4a604f5d4d9459a36993f5e92b53e8b0", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/3ddf170e4a604f5d4d9459a36993f5e92b53e8b0", "name": "https://git.kernel.org/stable/c/3ddf170e4a604f5d4d9459a36993f5e92b53e8b0", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/3fd4282d5f25c3c97fef3ef0b89b82ef4e2bc975", "name": "https://git.kernel.org/stable/c/3fd4282d5f25c3c97fef3ef0b89b82ef4e2bc975", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/3fd4282d5f25c3c97fef3ef0b89b82ef4e2bc975", "name": "https://git.kernel.org/stable/c/3fd4282d5f25c3c97fef3ef0b89b82ef4e2bc975", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/64a47cf634ae44e92be24ebc982410841093bd7b", "name": "https://git.kernel.org/stable/c/64a47cf634ae44e92be24ebc982410841093bd7b", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/64a47cf634ae44e92be24ebc982410841093bd7b", "name": "https://git.kernel.org/stable/c/64a47cf634ae44e92be24ebc982410841093bd7b", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/aea27a92a41dae14843f92c79e9e42d8f570105c", "name": "https://git.kernel.org/stable/c/aea27a92a41dae14843f92c79e9e42d8f570105c", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/aea27a92a41dae14843f92c79e9e42d8f570105c", "name": "https://git.kernel.org/stable/c/aea27a92a41dae14843f92c79e9e42d8f570105c", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nnet: micrel: Fix receiving the timestamp in the frame for lan8841\n\nThe blamed commit started to use the ptp workqueue to get the second\npart of the timestamp. And when the port was set down, then this\nworkqueue is stopped. But if the config option NETWORK_PHY_TIMESTAMPING\nis not enabled, then the ptp_clock is not initialized so then it would\ncrash when it would try to access the delayed work.\nSo then basically by setting up and then down the port, it would crash.\nThe fix consists in checking if the ptp_clock is initialized and only\nthen cancel the delayed work."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-06-19T14:15Z", "lastModifiedDate": "2024-11-21T09:26Z"}