{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2022-48880", "ASSIGNER": "cve@kernel.org"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://git.kernel.org/stable/c/50b3cdf8239b11545f311c4f7b89e0092e4feedb", "name": "https://git.kernel.org/stable/c/50b3cdf8239b11545f311c4f7b89e0092e4feedb", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/c965daac370f08a9b71d573a71d13cda76f2a884", "name": "https://git.kernel.org/stable/c/c965daac370f08a9b71d573a71d13cda76f2a884", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/d2dc110deabe7142b60ebeed689e67f92795ee24", "name": "https://git.kernel.org/stable/c/d2dc110deabe7142b60ebeed689e67f92795ee24", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nplatform/surface: aggregator: Add missing call to ssam_request_sync_free()\n\nAlthough rare, ssam_request_sync_init() can fail. In that case, the\nrequest should be freed via ssam_request_sync_free(). Currently it is\nleaked instead. Fix this."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-08-21T07:15Z", "lastModifiedDate": "2024-08-21T12:30Z"}